CREATE TABLE IF NOT EXISTS books (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255) NOT NULL,
    author        VARCHAR(255) NOT NULL,
    published_year            INTEGER NOT NULL
    );


